config/routes.rb
require 'resque/server'

Spot::Application.routes.draw do    
  scope :module => "api", :constraints => {:subdomain => /api\d*/}, :as => "api" do
    resources :places, :only => [:index] do
      get "search", :on => :collection
    end
    resources :registrations, :only => [:create, :destroy]
    resources :experiences, :only => [:index]
    resources :events, :only => [:create]
    resources :cities, :only => [:index]
    resources :users, :only => [:update, :show]
    resource :sessions, :only => [:new, :create, :destroy]
    resource :activity, :only => [:show], :controller => "activity"
    resources :notes, :only => [:show, :index, :create, :update, :destroy]
    resource :wishlist, :only => [:show] do
      resources :items, :only => [:create, :destroy], :controller => :wishlist_items
    end
  end
  
  scope :module => "site", :constraints => {:subdomain => /www|m|app|/} do
    resources :blog, :controller => "blog", :only => [:index, :show] do
      get :refresh, :on => :collection, :action => "refresh"
    end
    resources :previews, :only => [:create]
    resource :session, :only => [:new, :create, :destroy]
    resource :account, :only => [:new, :create, :show, :update, :destroy] do
      get "endpoint", :action => "endpoint", :on => :collection
    end
    resource :password_reset, :only => [:new, :create, :edit, :update]
    resources :cities, :only => [:show, :new] do
      get "calendar", :on => :member
      get "perks", :on => :member
      get "redirect", :on => :collection
    end
    resource :application, :only => [:create, :new, :update], :controller => "membership_applications"
    resources :registrations, :only => [:new, :show, :create, :destroy]
    resources :places, :only => [:show] do
      resources :events, :only => [:show]
    end
    resource :membership, :only => [:new, :create, :destroy] do 
      get "thanks", :action => "thanks", :on => :member
      get "endpoint", :action => "endpoint", :on => :collection
    end

    resources :onthehouse, :only => [:show], :as => :sweepstakes, :controller => :sweepstakes do
      get "rules", :on => :member
      post "enter", :on => :member
    end
    resource :widget, :only => [:show]
    resource :email, :only => [:show, :update] do
      delete "unsubscribe"
      match "mailchimp", :to => :mailchimp
      get "availability"
      get "existence"
    end
    resources :invite_requests, :only => [:create, :update]
    controller "home" do
      get "about", :action => "about"
      get "privacy", :action => "privacy"
      get "tos", :action => "tos"
      get "press", :action => "press"
      get "membership/about", :action => "about_membership", :as => "membership_about"
    end
    
    controller "mobile_app" do
      get "getspot", :action => "download"
      get "mobile/entrance", :action => "entrance", :as => "from_mobile_app"
      get "mobile/exit", :action => "exit", :as => "to_mobile_app"
    end
    
    controller "tracking" do
      get "/tracking/clear", :action => "clear", :as => "clear_tracking"
      get "/in", :action => "portal", :as => "portal"
      post "/uevent.:format", :action => "user_event", :as => "user_event"
      post "/aevent.:format", :action => "acquisition_event", :as => "acquisition_event"
    end
    get "/codes/:type/:code", :to => "codes#show"
    get "login" => redirect("/session/new")
    get "register" => redirect("/account/new")
    get "logout", :to => "sessions#destroy"
    get "/!/:id", :to => redirect { |params| ShortUrl.expand(params[:id]) || "/404.html" }, :as => "short"
    get "sitemap(.:format)", :to => "sitemaps#show", :constraints => {:format => :xml}, :as => "sitemap"
  end
  
  namespace "admin" do
    resources :places do
      resources :matches, :only => [:index, :create]
      get "search", :on => :collection
      put "dedupe", :on => :member
      get "matches", :on => :collection
      get "images", :on => :member
    end
    resources :activity_items, :only => [:index]
    resources :invite_requests, :only => [:index, :destroy] do
      put "trigger", :on => :member
    end
    resources :duplicates, :only => [:index, :create] do
      member do 
        put "resolve"
        put "ignore"
      end
    end
    resources :promotions, :only => [:index, :update, :destroy]
    resources :business_accounts, :only => [:index, :destroy] do 
      put "toggle", :on => :member
    end
    resources :businesses, :only => [:index, :destroy] do 
      put "toggle", :on => :member
    end
    resource :search, :only => [:new, :show], :controller => "search"
    resources :settings, :only => [:index, :create, :update, :destroy] do
      get "available", :on => :collection
    end
    resources :membership_codes, :only => [:index, :create, :destroy]
    namespace "acquisition" do
      resources :sources, :only => [:index, :create]
      resources :cohorts, :only => [:index]
      resources :sweepstakes
      resources :campaigns, :only => [:index, :create]
      root :to => "cohorts#index"
    end
    controller "home" do
      get "info"
      get "analysis"
    end
    resource :session_test, :only => [:new, :show], :controller => "session_test"
    root :to => "home#index"
  end
  
  namespace "biz" do
    resource :account, :only => [:new, :create, :show, :update]
    resources :businesses, :only => [:new, :create, :show, :edit, :update] do
      resources :promotions, :only => [:index, :create, :update, :destroy]
      resources :templates, :path => "promotions/templates", :controller => "promotion_templates", :only => [:index, :create, :update, :destroy]
      resources :codes, :only => [:index, :show], :controller => "promotion_codes" do
        get :lookup, :on => :collection
        get :mail, :on => :collection
        put :redeem, :on => :member
      end
      get :search, :on => :collection
      get :calendar, :on => :member
    end
    resource :contact, :only => [:new, :create]
    controller "home" do
      get "help"
    end
    get "faq", :to => "home#faq"
    get "tos", :to => "home#tos"
    get "widgets", :to => "home#widgets"
    root :to => "home#index"
  end
  
  mount Resque::Server.new, :at => "/admin/resque"
  
  get "upgrade", :to => "site/errors#upgrade", :as => "upgrade"
  get "404.html", :to => "site/errors#not_found", :as => "not_found"
  get "422.html", :to => "site/errors#unprocessable", :as => "unprocessable"
  get "500.html", :to => "site/errors#server_error", :as => "server_error"

  root :to => "site/home#index"
  
  match "*path", :to => "site/errors#not_found"
end

app/models/biz/discount_code.rb
class DiscountCode < PromotionCode
  validates :discount_percentage, :presence => true, :inclusion => PromotionTemplate::DISCOUNTS
  
  nested_attributes({:discount_percentage => :int}, {:in => :parameters})
  
  def set_attributes_from_event
    super
    self.discount_percentage = event.discount_percentage
  end
end

app/models/biz/discount_event.rb
class DiscountEvent < PromotionEvent
  validates :discount_percentage, :presence => true, :inclusion => PromotionTemplate::DISCOUNTS
  validates :average_spend, :presence => true, :numericality => {:greater_than_or_equal_to => 0}

  nested_attributes({:discount_percentage => :int, :average_spend => :int}, {:in => :parameters})
  
  def summary
    "#{count.pluralize('customer')} at #{discount_percentage}% off, #{timeframe}"
  end

  def savings(party_size)
    ((average_spend * party_size * discount_percentage)/100.0) - dollar_cost
  end

  def set_attributes_from_template
    super
    self.discount_percentage = template.discount_percentage if discount_percentage.to_i <= 0
    self.average_spend = template.average_spend if average_spend.to_i <= 0
  end

  def code_class
    DiscountCode
  end
end

app/models/biz/discount_template.rb
class DiscountTemplate < PromotionTemplate
  validates :discount_percentage, :inclusion => DISCOUNTS
  validates :average_spend, :presence => true, :numericality => {:greater_than_or_equal_to => 0}
  
  nested_attributes({:discount_percentage => :int, :average_spend => :int}, {:in => :parameters})

  def self.discounts
    unless @discounts
      @discounts = {}
      DISCOUNTS.each do |d|
        @discounts["#{d}%"] = d
      end
    end
    @discounts
  end
    
  def est_value
    average_spend.to_i > 0 ? average_spend.to_i * discount_percentage.to_i/100.0 : "N/A"
  end
  
  def summary
    "#{count.pluralize('customers')} per day at #{discount_percentage}% off, #{timeframe}"
  end
  
  def event_class
    DiscountEvent
  end
end

app/models/biz/generic_code.rb
class GenericCode < PromotionCode
  validates :description, :presence => true, :length => {:minimum => 10}
  nested_attributes({:description => :string}, {:in => :parameters})

  def set_attributes_from_event
    super
    self.description = event.description
  end
end

app/controllers/biz/accounts_controller.rb
class Biz::AccountsController < Biz::BaseController
  skip_before_filter :require_account, :except => [:show, :update]
  before_filter :require_no_account, :except => [:show, :update]
  
  def new
    @account = BusinessAccount.new
  end
  
  def create
    @account = BusinessAccount.register(params[:business_account])
    if @account.save
      warden.set_user @account.user
      redirect_to new_biz_business_path
    else
      flash.now[:error] = "Something's not right: #{@account.errors.full_messages.join(', ')}. Can you double check your entry?"
      @page_namespace = "biz_accounts_new"
      render :action => :new
    end
  end
  
  def show
  end
  
  def update
    current_account.attributes = params[:business_account]
    if current_account.save
      redirect_to biz_account_path
    else
      flash[:error] = "Sorry, there were errors with your submission."
      @page_namespace = "biz_accounts_show"
      render :action => "show"
    end
  end
end

app/controllers/biz/base_controller.rb
class Biz::BaseController < ApplicationController
  before_filter :require_account
  layout 'biz'
    
  private
    
  def current_account
    current_user.try(:business_account)
  end
  helper_method :current_account
  
  def require_account
    authenticate
    unless current_account
      store_location
      flash[:error] = current_user ? "Tell us about your business." : "Please sign in first."
      url = current_user ? new_biz_account_path : new_session_path
      Rails.logger.info("spot: redirecting from require_account to #{url}")
      redirect_to url
    end
  end

  def require_no_account
    if current_account
      authenticate
      url = biz_account_path
      Rails.logger.info("spot: redirecting from require_no_account to #{url}")
      redirect_to url 
    end
  end
end

app/controllers/biz/businesses_controller.rb
class Biz::BusinessesController < Biz::BaseController
  before_filter :require_business, :except => [:new, :create, :search]

  def new
  end

  def edit
  end
  
  def update
    @business.attributes = params[:business].except(:place_attributes)
    @business.place.attributes = params[:business][:place_attributes]
    if @business.verified? && @business.save
      redirect_to edit_biz_business_path(@business)
    else
      flash[:error] = @business.verified?? 
        "We had some errors with your submission." : 
        "Sorry, you need to be verified before you can edit your entry."
      @page_namespace = "biz_businesses_edit"
      render :action => :edit
    end
  end
  
  def create
    @business = current_account.claim(params[:business])
    if @business.save
      redirect_to biz_business_path(@business)
    else
      flash[:error] = @business.errors.full_messages
      redirect_to biz_account_path
    end
  end

  def search
    @search = PlaceSearch.from_params(params[:search])
    respond_to do |format|
      format.html
      format.js { render :json => { :html => render_to_string(:partial => "search") }}
    end
  end
    
  def show
  end
  
  def calendar
  end
  
  private
  
  def require_business
    @business = current_account.businesses.find(params[:id])
    redirect_to new_biz_business_path unless @business
  end
end

app/controllers/biz/contacts_controller.rb
class Biz::ContactsController < Biz::BaseController
  skip_before_filter :require_account

  def new
  end
  
  def create
    BusinessMailer.contact(current_account, params[:contact]).deliver!
    flash[:notice] = "Your message has been sent. We'll be in touch shortly."
    redirect_to current_account ? biz_account_path : biz_root_path
  end  
end

app/controllers/biz/deal_templates_controller.rb
class Biz::DealTemplatesController < Biz::BaseController
  before_filter :require_business

  def index
    @templates = @business.deal_templates.active.all
    respond_to do |format|
      format.js { render :json => {:success => true, :templates => @templates}}
    end
  end
  
  def create
    @template = @business.deal_templates.new(params[:template])
    respond_to do |format|
      if @template.save
        format.js { render :json => {:success => true, :template => @template} }
        format.html { redirect_to calendar_biz_business_path(@business) }
      else
        format.js { render :json => {:success => false, :error => @template.errors.full_messages.join(" ")} }
      end
    end
  end
    
  def destroy
    @template = @business.deal_templates.find(params[:id])
    @template.removed!
    respond_to do |format|
      format.js { render :json => {:success => true} }
      format.html { redirect_to calendar_biz_business_path(@business) }
    end
  end

  private
  
  def require_business
    @business = current_account.businesses.find(params[:business_id])
    redirect_to new_biz_business_path unless @business
  end
end

app/controllers/biz/deals_controller.rb
class Biz::DealsController < Biz::BaseController
  before_filter :require_business

  def index
    @events = @business.deal_events.all
    respond_to do |format|
      format.js { render :json => {:success => true, :events => @events.group_by { |e| e.date.to_s() }} }
    end
  end
  
  def create
    @event = @business.deal_events.new(params[:event])
    respond_to do |format|
      if @event.save
        format.js { render :json => {:success => true, :event => @event} }
        format.html { redirect_to calendar_biz_business_path(@business) }
      else
        format.js { render :json => {:success => false, :error => @event.errors.full_messages.join(", ")} }
      end
    end
  end
  
  def destroy
    @event = @business.deal_events.find(params[:id])
    @event.remove!
    respond_to do |format|
      format.js { render :json => {:success => true, :event => @event.destroyed?? nil : @event} }
      format.html { redirect_to calendar_biz_business_path(@business) }
    end
  end
  
  def update
  end

  private
  
  def require_business
    @business = current_account.businesses.find(params[:business_id])
    redirect_to new_biz_business_path unless @business
  end
end

app/controllers/biz/discount_codes_controller.rb
class Biz::DiscountCodesController < Biz::BaseController
  before_filter :require_business
  
  def index
    @date = Time.at(params[:date_seconds].to_f).to_date if params[:date_seconds]
    @date ||= Date.today
    @events = @business.deal_events.on_date(@date).includes(:deal_codes => :owner).all
    respond_to do |format|
      format.html
      format.js { render :json => {:html => render_to_string(:partial => "codes")}}
    end
  end
  
  def lookup
    @code = @business.deal_codes.where(:code => params[:code]).first
    respond_to do |format|
      format.html
      format.js { render :json => {:html => render_to_string(:partial => "code", :object => @code)}}
    end
  end

  def mail
    success = @business.deliver_deal_codes_for! params[:date]
    respond_to do |format|
      format.html { redirect_to biz_business_codes_path(@business) }
      format.js { render :json => {:success => success, :flash => success ? "Discount codes sent. Check your email." : "No codes for that date."} }
    end
  end
  
  def redeem
    @code = @business.deal_codes.find(params[:id])
    @code.redeem!
    @event = @code.deal_event
    respond_to do |format|
      format.html { redirect_to biz_business_codes_path(@business) }
      format.js { render :json => { :event_id => @event.id,
                                    :code_id => @code.id,
                                    :code => render_to_string(:partial => "code", :object => @code),
                                    :event => render_to_string(:partial => "event", :object => @event) } }
    end
  end

  private
  
  def require_business
    @business = current_account.businesses.find(params[:business_id])
    redirect_to new_biz_business_path unless @business
  end
end

app/controllers/biz/home_controller.rb
class Biz::HomeController < Biz::BaseController
  skip_before_filter :require_account, :only => [:index, :faq, :tos]
  before_filter :require_no_account, :only => [:index]
  
  def index
  end
  
  def faq
    @faqs = YAML.load_file("#{Rails.root}/db/bizfaqs.yml")["faqs"]
  end
  
  def tos
  end
  
  def widgets
  end
end

app/controllers/biz/previews_controller.rb
class Biz::PreviewsController < Biz::BaseController
  skip_before_filter :require_admin
  skip_before_filter :require_account
  
  layout 'site'
  
  def index
  end
  
  def create
    @preview = PreviewSignup.signup(params[:preview])
    if @preview.save
      flash[:notice] = "Thank you for your interest. We'll be in touch."
    else
      flash[:error] = "Sorry, there was an error with your submission, please try again."
    end
    redirect_to root_path
  end
  
  def show
    @preview = PreviewSignup.find_by_rid(params[:preview_id])
  end
end

app/views/biz/promotion_templates/_form.html.haml
#newpromotiontpl.hidden
  %ul.tabbar.pillbox.orange
    %li.pill.first
      %a.tab.active.inpopover{:href => "#discountpromotpl"} discount
    %li.pill.last
      %a.tab.inpopover{:href => "#genericpromotpl"} special event
      
  =spot_form_for :discount, :url => biz_business_templates_path(@business), :display => "light inlinelabels", :ul_id => "discountpromotpl", :html => {'data-validate' => true, :class => "newtplform"} do |f|
    =f.hidden_field :type, :value => "DiscountTemplate"
    .details
      =f.text_field :name, :placeholder => "promotion name", :required => true
      %li.note give your promotion a name to easily remember it by.
      =f.text_field :count, :class => "short", :required => true, :min => 0, :max => 1000, :label => "customers per day :"
      =f.select :discount_percentage, DiscountTemplate.discounts, {:prompt => "--", :label => "discount percent :"}, :required => true
      %li.text.select.labelled
        .label=label_tag 'discount[start_time]', 'time of day :'
        .input_container
          =select_hour nil, {:field_name => "start_time", :prefix => 'discount', :twelve_hour => true, :offset => 6, :prompt => "--"}, {:required => true}
          \-
          =select_hour nil, {:field_name => "end_time", :prefix => 'discount', :twelve_hour => true, :offset => 7, :prompt => "--"}, {:required => true}
      =f.text_field :average_spend, :class => "abbrev", :required => true, :min => 0, :label => "avg. spend per person :"
      %li.note help us value this promotion. how much do your customers usually spend?
    %hr
    %li.description_title
      =label_tag 'discount[description]', "Describe Your Promotion"
    %li.note tell our members why they should want this. be colorful! no restrictions or limitations please
    =f.text_area :description, :placeholder => "promotion description"
    =button_tag :class => "bottom btngrypill" do
      Save Promotion

  =spot_form_for :generic, :url => biz_business_templates_path(@business), :display => "light hidden inlinelabels", :ul_id => "genericpromotpl", :html => {'data-validate' => true, :class => "newtplform"} do |f|
    =f.hidden_field :type, :value => "GenericTemplate"
    .details
      =f.text_field :name, :placeholder => "promotion name", :required => true
      %li.note give your promotion a name to easily remember it by.
      =f.text_field :count, :class => "short", :required => true, :min => 0, :max => 1000, :label => "customers per day :"
      %li.text.select.labelled
        .label=label_tag 'generic[start_time]', 'time of day :'
        .input_container
          =select_hour nil, {:field_name => "start_time", :prefix => 'generic', :twelve_hour => true, :offset => 6, :prompt => "--"}, {:required => true}
          \-
          =select_hour nil, {:field_name => "end_time", :prefix => 'generic', :twelve_hour => true, :offset => 7, :prompt => "--"}, {:required => true}
    %li.description_title
      =label_tag 'generic[description]', "Describe Your Promotion"
    =f.text_area :description, :placeholder => "promotion"
    %li.note what's the promotion? what are you offering?
    %hr
    .details
      %h3.center Help Us Understand
      =f.text_field :value, :class => "abbrev", :label => "monetary value :", :prepend => "$"
      %li.note what is the value of your offer? (optional)
      =f.text_field :cost, :class => "abbrev", :label => "cost :", :prepend => "$"
      %li.note what will this cost our members? (optional)
    =button_tag :class => "bottom btngrypill" do
      Save Promotion

app/views/biz/promotion_templates/_template.html.haml
%li.template{'data-id' => template.try(:id) || '${id}'}
  .color{:style => "background:#{template.try(:color) || '${color}'}"}
  %h2=template.try(:name) || '${name}'
  %h3=template.try(:summary) || '${summary}'
  .description=template.try(:description) || '${description}'
  ="{{if status == #{PromotionTemplate::APPROVED_STATUS}}}"
  .approval.approved{'data-jstooltip' => "Approved!"}
    Approved
  ="{{else status == #{PromotionTemplate::PENDING_STATUS}}}"
  .approval.pending{'data-jstooltip' => "Pending Approval. Your promotion won't be available until it's approved."}
    Pending Approval
  {{else}}
  .approval.rejected{'data-jstooltip' => "Rejected, contact julia@spotmembers.com to resolve."}
    Rejected
  {{/if}}
  .controls.clearfix
    =form_tag CGI.unescape(biz_business_template_path(@business, '${id}')), :method => "delete", :class => "remove", 'data-confirm' => "Are you sure you want to delete '${name}'? This action is irreversible." do
      =button_tag :class => "withx btngrypill" do
        %span.redx
          &times;
        Delete
    .link.finish Finish