config/routes.rb
require 'resque/server'

Spot::Application.routes.draw do    
  scope :module => "api", :constraints => {:subdomain => /api\d*/}, :as => "api" do
    resources :places, :only => [:index] do
      get "search", :on => :collection
    end
    resources :registrations, :only => [:create, :destroy]
    resources :experiences, :only => [:index]
    resources :events, :only => [:create]
    resources :cities, :only => [:index]
    resources :users, :only => [:update, :show]
    resource :sessions, :only => [:new, :create, :destroy]
    resource :activity, :only => [:show], :controller => "activity"
    resources :notes, :only => [:show, :index, :create, :update, :destroy]
    resource :wishlist, :only => [:show] do
      resources :items, :only => [:create, :destroy], :controller => :wishlist_items
    end
  end
  
  scope :module => "site", :constraints => {:subdomain => /www|m|app|/} do
    resources :blog, :controller => "blog", :only => [:index, :show] do
      get :refresh, :on => :collection, :action => "refresh"
    end
    resources :previews, :only => [:create]
    resource :session, :only => [:new, :create, :destroy]
    resource :account, :only => [:new, :create, :show, :update, :destroy] do
      get "endpoint", :action => "endpoint", :on => :collection
    end
    resource :password_reset, :only => [:new, :create, :edit, :update]
    resources :cities, :only => [:show, :new] do
      get "calendar", :on => :member
      get "perks", :on => :member
      get "redirect", :on => :collection
    end
    resource :application, :only => [:create, :new, :update], :controller => "membership_applications"
    resources :registrations, :only => [:new, :show, :create, :destroy]
    resources :places, :only => [:show] do
      resources :events, :only => [:show]
    end
    resource :membership, :only => [:new, :create, :destroy] do 
      get "thanks", :action => "thanks", :on => :member
      get "endpoint", :action => "endpoint", :on => :collection
    end

    resources :onthehouse, :only => [:show], :as => :sweepstakes, :controller => :sweepstakes do
      get "rules", :on => :member
      post "enter", :on => :member
    end
    resource :widget, :only => [:show]
    resource :email, :only => [:show, :update] do
      delete "unsubscribe"
      match "mailchimp", :to => :mailchimp
      get "availability"
      get "existence"
    end
    resources :invite_requests, :only => [:create, :update]
    controller "home" do
      get "about", :action => "about"
      get "privacy", :action => "privacy"
      get "tos", :action => "tos"
      get "press", :action => "press"
      get "membership/about", :action => "about_membership", :as => "membership_about"
    end
    
    controller "mobile_app" do
      get "getspot", :action => "download"
      get "mobile/entrance", :action => "entrance", :as => "from_mobile_app"
      get "mobile/exit", :action => "exit", :as => "to_mobile_app"
    end
    
    controller "tracking" do
      get "/tracking/clear", :action => "clear", :as => "clear_tracking"
      get "/in", :action => "portal", :as => "portal"
      post "/uevent.:format", :action => "user_event", :as => "user_event"
      post "/aevent.:format", :action => "acquisition_event", :as => "acquisition_event"
    end
    get "/codes/:type/:code", :to => "codes#show"
    get "login" => redirect("/session/new")
    get "register" => redirect("/account/new")
    get "logout", :to => "sessions#destroy"
    get "/!/:id", :to => redirect { |params| ShortUrl.expand(params[:id]) || "/404.html" }, :as => "short"
    get "sitemap(.:format)", :to => "sitemaps#show", :constraints => {:format => :xml}, :as => "sitemap"
  end
  
  namespace "admin" do
    resources :places do
      resources :matches, :only => [:index, :create]
      get "search", :on => :collection
      put "dedupe", :on => :member
      get "matches", :on => :collection
      get "images", :on => :member
    end
    resources :activity_items, :only => [:index]
    resources :invite_requests, :only => [:index, :destroy] do
      put "trigger", :on => :member
    end
    resources :duplicates, :only => [:index, :create] do
      member do 
        put "resolve"
        put "ignore"
      end
    end
    resources :promotions, :only => [:index, :update, :destroy]
    resources :business_accounts, :only => [:index, :destroy] do 
      put "toggle", :on => :member
    end
    resources :businesses, :only => [:index, :destroy] do 
      put "toggle", :on => :member
    end
    resource :search, :only => [:new, :show], :controller => "search"
    resources :settings, :only => [:index, :create, :update, :destroy] do
      get "available", :on => :collection
    end
    resources :membership_codes, :only => [:index, :create, :destroy]
    namespace "acquisition" do
      resources :sources, :only => [:index, :create]
      resources :cohorts, :only => [:index]
      resources :sweepstakes
      resources :campaigns, :only => [:index, :create]
      root :to => "cohorts#index"
    end
    controller "home" do
      get "info"
      get "analysis"
    end
    resource :session_test, :only => [:new, :show], :controller => "session_test"
    root :to => "home#index"
  end
  
  namespace "biz" do
    resource :account, :only => [:new, :create, :show, :update]
    resources :businesses, :only => [:new, :create, :show, :edit, :update] do
      resources :promotions, :only => [:index, :create, :update, :destroy]
      resources :templates, :path => "promotions/templates", :controller => "promotion_templates", :only => [:index, :create, :update, :destroy]
      resources :codes, :only => [:index, :show], :controller => "promotion_codes" do
        get :lookup, :on => :collection
        get :mail, :on => :collection
        put :redeem, :on => :member
      end
      get :search, :on => :collection
      get :calendar, :on => :member
    end
    resource :contact, :only => [:new, :create]
    controller "home" do
      get "help"
    end
    get "faq", :to => "home#faq"
    get "tos", :to => "home#tos"
    get "widgets", :to => "home#widgets"
    root :to => "home#index"
  end
  
  mount Resque::Server.new, :at => "/admin/resque"
  
  get "upgrade", :to => "site/errors#upgrade", :as => "upgrade"
  get "404.html", :to => "site/errors#not_found", :as => "not_found"
  get "422.html", :to => "site/errors#unprocessable", :as => "unprocessable"
  get "500.html", :to => "site/errors#server_error", :as => "server_error"

  root :to => "site/home#index"
  
  match "*path", :to => "site/errors#not_found"
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < Admin::BaseController
  before_filter :require_place, :only => [:edit, :update, :destroy, :images, :dedupe]
  respond_to :html
  
  def index
    @places = Place.filter(params)
    respond_with(@places)
  end
  
  def search
    params[:per_page] ||= 10 if request.xhr?
    @places = Place.search(params[:term], :star => true, :match_mode => :any, :page => params[:page], :per_page => params[:per_page])
    respond_to do |format|
      format.js { render :json => @places }
      format.html
    end
  end
  
  def matches
    @places = Place.filter(params)
    @externals = ExternalPlace.associated_with(@places.collect { |p| p.id })
  end
  
  def new
    @place = Place.new
    respond_with(@place)
  end

  def dedupe
    flash[:notice] = "Deduping #{@place.name}"
    Resque.enqueue(Jobs::PlaceDeduper, @place.id)
    redirect_to edit_admin_place_path(@place)
  end

  def create
    @place = Place.new(params[:place])
    success = @place.save
    respond_to do |format|
      format.html { redirect_to admin_place_path(@place) }
      format.js { render :json => @place }
    end
  end
  
  def show
    redirect_to edit_admin_place_path(params[:id])
  end
  
  def edit
  end
  
  def update
    @place.attributes = params[:place]
    success = @place.save
    respond_to do |format|
      format.html do 
        if success
          flash[:notice] = "#{@place.name} Updated!"
          redirect_to(edit_admin_place_path(@place))
        else
          flash.now[:error] =  "There were errors with your submission"
          render(:action => "edit")
        end
      end
      format.js { render :json => @place.as_json(:default_images => true, :processed_images => true) }
    end
  end
  
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to admin_places_path }
    end
  end
  
  def images
    @search = ImageSearch.new(@place, request)
    @images = @search.results
    respond_to do |format|
      format.js { render :json => { :html => render_to_string(:partial => "images") } }
    end
  end
  
  private
  
  def require_place
    @place = Place.find(params[:id])
  end
end

app/controllers/api/places_controller.rb
class Api::PlacesController < Api::BaseController
  skip_before_filter :require_user
  
  def index
    ids = params[:ids].to_s.split(',')
    @places = Place.where(:id => ids).all.hash_by { |p| p.id.to_s }
    @places = ids.collect { |id| @places[id.to_s] }
    ExternalPlace.add_to(@places)    
    record_user_event("api place load")
    render :json => @places.as_json(:external_places => true)
  end
  
  def search
    @search = PlaceSearch.from_params(params)
    if @search.save
      response.headers["X-Search-ID"] = @search.id.to_s
      record_user_event("api place search")
      render :json => @search.as_json(:external_places => true)
    else
      render :json => []
    end
  end
end

app/controllers/site/places_controller.rb
class Site::PlacesController < Site::BaseController
  def show
    @place = Place.find(params[:id])
    @place = @place.canonical
  end
end

app/helpers/place_helper.rb
module PlaceHelper
  def external_place_url(place)
    case place
    when ExternalPlace::YelpPlace
      "http://www.yelp.com/biz/#{place.yelp_id}"
    when ExternalPlace::GooglePlace
      "http://maps.google.com/maps/place?cid=#{place.cid}"
    when ExternalPlace::GowallaPlace
      "http://www.gowalla.com/spots/#{place.gowalla_id}"      
    when ExternalPlace::FacebookPlace
      "http://www.facebook.com/pages/#{place.name.parameterize}/#{place.facebook_id}"
    when ExternalPlace::FoursquarePlace
      "http://www.foursquare.com/venue/#{place.foursquare_id}"
    else
      nil
    end
  end
end

app/views/admin/places/_detail.html.haml
.place.detail{:id => dom_id(@place)}
  .left
    =render :partial => "shared/places/iphone", :object => @place, :as => :place
    -unless @place.new_record?
      .subtext
        -if @place.image_attribution.present?
          .attribution
            ="Image Courtesy Of "
            =link_to "#{@place.image_attribution["source"].titlecase} API", @place.image_attribution["owner_url"], :target => "_new"       
        %p.page_link=link_to "spot page", ShortUrl.shorten(place_path(@place))
        .external_places
          -ExternalPlace.sources.each do |src|
            -if ep = place.external_place(src)
              =link_to "#{src.to_sym}", external_place_url(ep), :target => "_new", :class => "matched"
            -else
              =link_to "#{src.to_sym}", admin_place_matches_path(@place, :src => src.to_sym), :class => "potential"

  .sidebar
    .map_message
    .map=image_tag(google_static_map_url(@place, :size => "420x250"))
    .latlng="@#{@place.to_lat_lng}"
    =render :partial => "form", :object => @place, :as => :place

  
  .duplication
    -if @place.duplicate?
      %h2 Duplicate of...
      %p.canonical
        =link_to(@place.canonical.id, admin_place_path(@place.canonical)) + '.'
        ="#{@place.canonical.name} #{@place.canonical.address}"

    -elsif @place.duplicates.present?
      %h2 Also Known As...
      -@place.duplicates.each do |dupe|
        %p.duplicate
          =link_to(dupe.id, admin_place_path(dupe)) + '.'
          ="#{dupe.name} #{dupe.address}"
    
    -unless @place.new_record?
      =link_to "Run Deduping", dedupe_admin_place_path(@place), "data-method" => "put"
      =spot_form_for :duplicate, :url => admin_duplicates_path, :display => "light", :html => {"data-confirm" => "Are you sure? This is not reversible"} do |f|
        =f.hidden_field :place_1_id, :value => @place.id
        =f.number_field :place_2_id, :label => "Mark Duplicate : ", :placeholder => "duplicate place id", :required => true
      

app/views/admin/places/_form.html.haml
=spot_form_for [:admin, @place], :display => "light inlinelabels", :html => {:multipart => true} do |f|
  =f.text_field :name, :label => "Name :", :required => true, :class => "name_field", :hint => "what is the place name?"
  =f.text_field 'address_lines[0]', :value => @place.address_lines[0], :label => "Address (line 1) :", :hint => "what's the street address?", :required => true, :class => "address_field"
  =f.text_field 'address_lines[1]', :value => @place.address_lines[1], :label => "Address (line 2) :", :hint => "and the city, region, zip?", :required => true, :class => "address_field"
  =f.text_field :twitter, :label => "Twitter :", :hint => "what is the twitter handle?", :pattern => "^@\\w+$"
  =f.text_field :website, :label => "Website :", :hint => "what is the place's website?"
  =f.text_field :city, :label => "City :", :hint => "what city is the place in?"
  =f.text_field :region, :label => "Region :", :hint => "what state is the place in?"
  =f.text_field :country, :label => "Country :", :hint => "what country is the place in?"
  =f.phone_field :phone_number, :label => "Phone Number :", :hint => "what is the place's number?"
  =f.text_field :lat, :min => -90, :max => 90, :label => "Lat :", :hint => "do you really know the lat?"
  =f.text_field :lng, :min => -180, :max => 180, :label => "Lng :", :hint => "do you really know the lng?"
  =f.file_field :image, :label => "Choose an Image :"
  =f.text_field :external_image_url, :label => "Image URL :", :hint => "an image from the tubes?"
  %li.buttons
    =button_tag :class => "btngrypill300x30" do
      Save Changes
    -unless @place.new_record?
      %p=link_to "Delete", admin_place_path(@place), "data-confirm" => "Are you sure you want to delete #{@place.name}?", "data-method" => "delete"
    

app/views/admin/places/_images.html.haml
.image_search_results
  .preview
  %ul.form_wrapper
    =form_tag images_admin_place_path(@place), :method => :get, :class => "custom_form" do
      %li
        =label_tag :query, "Search For : "
        =text_field_tag :query
        =button_tag :class => "rndblk_80x26" do
          Search
  .sections
    -@images.each do |title, images|
      .section
        %h2=title
        -images.each do |image|
          =form_for [:admin, @place], :html => {"data-place-id" => @place.id} do |f|
            =f.hidden_field :external_image_url, :value => image.url
            =f.fields_for :image_attribution do |ia|
              =ia.hidden_field :source, :value => image.source
              =ia.hidden_field :owner_url, :value => image.owner_url
            .image_potential{:class => image.source, :style => "background-image: url(#{image.url(:size => 'm')});", 'data-url' => image.url(:size => "l")}

app/views/admin/places/_table.html.haml
%table.data
  %thead
    %tr
      %th Image
      %th Id
      %th Name
      %th Address
      %th Wishlists
      %th Lat, Lng
      %th Actions
  %tbody
    -@places.to_a.each do |place|
      %tr.center.place{:id => dom_id(place), :class => cycle("even", "odd")}
        %td= image_tag place.image.url(:i234x168), :size => "58x42", :class => "place_image clickable", :alt => "", :title => "Click to Change", 'data-img-src' => place.image.processed_url(:i234x168)
        %td= place.id
        %td= place.name
        %td= place.flat_address
        %td= place.wishlist_count.to_i
        %td= place.to_lat_lng
        %td
          =link_to "Edit", edit_admin_place_path(place)
          =link_to "Page", place_path(place)            

app/views/admin/places/edit.html.haml
.manager
  .breadcrumb
    =link_to "Places", admin_places_path
    &rarr;
    =@place.name
  =render :partial => "detail", :object => @place, :as => :place

app/views/admin/places/index.html.haml
-filters = params.slice('filter')
.manager
  .top.clearfix
    .pagination
      -unless @places.last_page?
        .next=link_to "Next &rarr;".html_safe, admin_places_path(filters.merge(:page => @places.current_page + 1))
      -unless @places.first_page?
        .previous=link_to "&larr; Previous".html_safe, admin_places_path(filters.merge(:page => @places.current_page - 1))
    %h1.title="#{@places.total_count} Places"
    .links
      =link_to "Image Queue", admin_places_path(filters.merge(:filter => 3))
      =link_to "Imageless", admin_places_path(filters.merge(:filter => 2))
      =link_to "Wishlisted", admin_places_path(filters.merge(:filter => 1))
      =link_to "Processing", admin_places_path(filters.merge(:filter => 4))
      =link_to "All", admin_places_path
      =link_to "New", new_admin_place_path
  =render :partial => "table", :object => @places, :as => :places
  .pagination.bottom
    -unless @places.last_page?
      .next=link_to "Next &rarr;".html_safe, admin_places_path(params.slice('filter').merge(:page => @places.current_page + 1))
    -unless @places.first_page?
      .previous=link_to "&larr; Previous".html_safe, admin_places_path(params.slice('filter').merge(:page => @places.current_page - 1))

app/views/admin/places/matches.html.haml
.manager
  .top.clearfix
    .pagination
      -unless @places.last_page?
        .next=link_to "Next &rarr;".html_safe, matches_admin_places_path(:filter => params[:filter], :page => @places.current_page + 1)
      -unless @places.first_page?
        .previous=link_to "&larr; Previous".html_safe, matches_admin_places_path(:filter => params[:filter], :page => @places.current_page - 1)
    %h1.title="#{@places.total_count} Places"
    .links
      =link_to "Image Queue", matches_admin_places_path(:filter => 3)
      =link_to "Imageless", matches_admin_places_path(:filter => 2)
      =link_to "Wishlisted", matches_admin_places_path(:filter => 1)
      =link_to "All", matches_admin_places_path
  %table.data
    %thead
      %tr
        %th Spot
        -ExternalPlace.sources.each do |src|
          %th=src.to_sym.to_s.titlecase
    %tbody
      -@places.each do |place|
        %tr
          %td.place
            .name=link_to place.name, admin_place_path(place)
            .address=place.flat_address
            .position=place.to_lat_lng.to_s
          -ExternalPlace.sources.each do |src|
            -ep = @externals[place.id][src.to_sym]
            %td{:class => conditionally('filled', ep)}
              -if ep
                -proximity = PlaceMatch.proximity(place, ep)
                .name=link_to "#{ep.name}", external_place_url(ep), :target => "_new"
                .address=place.flat_address
                .distance="#{proximity.geo_distance.round} m"
                -if src.to_sym != :google
                  .links=link_to "edit", admin_place_matches_path(place, :src => src.to_sym)
              -elsif src.to_sym != :google
                =link_to "match #{src.to_sym}", admin_place_matches_path(place, :src => src.to_sym)
  .pagination
    -unless @places.last_page?
      .next=link_to "Next &rarr;".html_safe, matches_admin_places_path(:filter => params[:filter], :page => @places.current_page + 1)
    -unless @places.first_page?
      .previous=link_to "&larr; Previous".html_safe, matches_admin_places_path(:filter => params[:filter], :page => @places.current_page - 1)

app/views/admin/places/new.html.haml
.manager
  .breadcrumb
    =link_to "Places", admin_places_path
    &rarr;
    New Place
  =render :partial => "detail", :object => @place, :as => :place