config/routes.rb
require 'resque/server'

Spot::Application.routes.draw do    
  scope :module => "api", :constraints => {:subdomain => /api\d*/}, :as => "api" do
    resources :places, :only => [:index] do
      get "search", :on => :collection
    end
    resources :registrations, :only => [:create, :destroy]
    resources :experiences, :only => [:index]
    resources :events, :only => [:create]
    resources :cities, :only => [:index]
    resources :users, :only => [:update, :show]
    resource :sessions, :only => [:new, :create, :destroy]
    resource :activity, :only => [:show], :controller => "activity"
    resources :notes, :only => [:show, :index, :create, :update, :destroy]
    resource :wishlist, :only => [:show] do
      resources :items, :only => [:create, :destroy], :controller => :wishlist_items
    end
  end
  
  scope :module => "site", :constraints => {:subdomain => /www|m|app|/} do
    resources :blog, :controller => "blog", :only => [:index, :show] do
      get :refresh, :on => :collection, :action => "refresh"
    end
    resources :previews, :only => [:create]
    resource :session, :only => [:new, :create, :destroy]
    resource :account, :only => [:new, :create, :show, :update, :destroy] do
      get "endpoint", :action => "endpoint", :on => :collection
    end
    resource :password_reset, :only => [:new, :create, :edit, :update]
    resources :cities, :only => [:show, :new] do
      get "calendar", :on => :member
      get "perks", :on => :member
      get "redirect", :on => :collection
    end
    resource :application, :only => [:create, :new, :update], :controller => "membership_applications"
    resources :registrations, :only => [:new, :show, :create, :destroy]
    resources :places, :only => [:show] do
      resources :events, :only => [:show]
    end
    resource :membership, :only => [:new, :create, :destroy] do 
      get "thanks", :action => "thanks", :on => :member
      get "endpoint", :action => "endpoint", :on => :collection
    end

    resources :onthehouse, :only => [:show], :as => :sweepstakes, :controller => :sweepstakes do
      get "rules", :on => :member
      post "enter", :on => :member
    end
    resource :widget, :only => [:show]
    resource :email, :only => [:show, :update] do
      delete "unsubscribe"
      match "mailchimp", :to => :mailchimp
      get "availability"
      get "existence"
    end
    resources :invite_requests, :only => [:create, :update]
    controller "home" do
      get "about", :action => "about"
      get "privacy", :action => "privacy"
      get "tos", :action => "tos"
      get "press", :action => "press"
      get "membership/about", :action => "about_membership", :as => "membership_about"
    end
    
    controller "mobile_app" do
      get "getspot", :action => "download"
      get "mobile/entrance", :action => "entrance", :as => "from_mobile_app"
      get "mobile/exit", :action => "exit", :as => "to_mobile_app"
    end
    
    controller "tracking" do
      get "/tracking/clear", :action => "clear", :as => "clear_tracking"
      get "/in", :action => "portal", :as => "portal"
      post "/uevent.:format", :action => "user_event", :as => "user_event"
      post "/aevent.:format", :action => "acquisition_event", :as => "acquisition_event"
    end
    get "/codes/:type/:code", :to => "codes#show"
    get "login" => redirect("/session/new")
    get "register" => redirect("/account/new")
    get "logout", :to => "sessions#destroy"
    get "/!/:id", :to => redirect { |params| ShortUrl.expand(params[:id]) || "/404.html" }, :as => "short"
    get "sitemap(.:format)", :to => "sitemaps#show", :constraints => {:format => :xml}, :as => "sitemap"
  end
  
  namespace "admin" do
    resources :places do
      resources :matches, :only => [:index, :create]
      get "search", :on => :collection
      put "dedupe", :on => :member
      get "matches", :on => :collection
      get "images", :on => :member
    end
    resources :activity_items, :only => [:index]
    resources :invite_requests, :only => [:index, :destroy] do
      put "trigger", :on => :member
    end
    resources :duplicates, :only => [:index, :create] do
      member do 
        put "resolve"
        put "ignore"
      end
    end
    resources :promotions, :only => [:index, :update, :destroy]
    resources :business_accounts, :only => [:index, :destroy] do 
      put "toggle", :on => :member
    end
    resources :businesses, :only => [:index, :destroy] do 
      put "toggle", :on => :member
    end
    resource :search, :only => [:new, :show], :controller => "search"
    resources :settings, :only => [:index, :create, :update, :destroy] do
      get "available", :on => :collection
    end
    resources :membership_codes, :only => [:index, :create, :destroy]
    namespace "acquisition" do
      resources :sources, :only => [:index, :create]
      resources :cohorts, :only => [:index]
      resources :sweepstakes
      resources :campaigns, :only => [:index, :create]
      root :to => "cohorts#index"
    end
    controller "home" do
      get "info"
      get "analysis"
    end
    resource :session_test, :only => [:new, :show], :controller => "session_test"
    root :to => "home#index"
  end
  
  namespace "biz" do
    resource :account, :only => [:new, :create, :show, :update]
    resources :businesses, :only => [:new, :create, :show, :edit, :update] do
      resources :promotions, :only => [:index, :create, :update, :destroy]
      resources :templates, :path => "promotions/templates", :controller => "promotion_templates", :only => [:index, :create, :update, :destroy]
      resources :codes, :only => [:index, :show], :controller => "promotion_codes" do
        get :lookup, :on => :collection
        get :mail, :on => :collection
        put :redeem, :on => :member
      end
      get :search, :on => :collection
      get :calendar, :on => :member
    end
    resource :contact, :only => [:new, :create]
    controller "home" do
      get "help"
    end
    get "faq", :to => "home#faq"
    get "tos", :to => "home#tos"
    get "widgets", :to => "home#widgets"
    root :to => "home#index"
  end
  
  mount Resque::Server.new, :at => "/admin/resque"
  
  get "upgrade", :to => "site/errors#upgrade", :as => "upgrade"
  get "404.html", :to => "site/errors#not_found", :as => "not_found"
  get "422.html", :to => "site/errors#unprocessable", :as => "unprocessable"
  get "500.html", :to => "site/errors#server_error", :as => "server_error"

  root :to => "site/home#index"
  
  match "*path", :to => "site/errors#not_found"
end

app/models/acquisition/acquisition_campaign.rb
class AcquisitionCampaign < ActiveRecord::Base
  has_many :acquisition_sources
  validates :category, :presence => true
  validates :name, :presence => true
  
  def self.filter(params)
    finder = self
    finder.page(params[:page]).per(params[:per_page])
  end
end

app/models/acquisition/acquisition_cohort.rb
class AcquisitionCohort < ActiveRecord::Base
  belongs_to :acquisition_source
  belongs_to :acquisition_campaign
    
  def self.clicked!(campaign, source, user)
    campaign_cohort(campaign).clicked!(user)
    source_cohort(source).clicked!(user)
  end

  def self.email_acquired!(campaign, source)
    campaign_cohort(campaign).email_acquired!
    source_cohort(source).email_acquired!
  end

  def self.applied!(campaign, source)
    campaign_cohort(campaign).applied!
    source_cohort(source).applied!
  end

  def self.signup!(campaign, source)
    campaign_cohort(campaign).signup!
    source_cohort(source).signup!
  end

  def self.member!(campaign, source, membership)
    campaign_cohort(campaign).member!(membership)
    source_cohort(source).member!(membership)
  end

  def self.registration!(campaign, source)
    campaign_cohort(campaign).registration!
    source_cohort(source).registration!
  end

  def self.unsubscribed!(campaign, source)
    campaign_cohort(campaign).registration!
    source_cohort(source).registration!
  end
  
  def self.campaign_cohort(campaign)
    date ||= Time.now.utc.to_date
    find_or_create_by_date_and_acquisition_campaign_id_and_acquisition_source_id(
      date,
      campaign.id,
      nil
    )
  end

  def self.source_cohort(source)
    date ||= Time.now.utc.to_date
    find_or_create_by_date_and_acquisition_campaign_id_and_acquisition_source_id(
      date,
      source.acquisition_campaign_id,
      source.id
    )
  end
  
  def clicked!(user)
    count!(user.try(:member?) ? :member_clicks : :nonmember_clicks)
  end
  
  def email_acquired!
    count!(:emails)
  end

  def signup!
    count!(:signups)
  end
  
  def applied!
    count!(:signups)
  end
  
  def member!(membership)
    count!(:memberships)
    count!( membership.payment_method.billing_period == 1 ? 
              :monthly_subscribers : 
              :annual_subscribers) if membership.payment_method.respond_to?(:billing_period)
              
  end

  def registration!
    count!(:registrations)
  end
  
  def unsubscribed!
    count!(:unsubscriptions)
  end

  private
  
  def count!(field, amount=1)
    self.class.update_counters(id, field => amount)
  end
end

app/models/acquisition/acquisition_event.rb
class AcquisitionEvent < ActiveRecord::Base
  belongs_to :email_subscriptions
  belongs_to :acquisition_source
  validates :event_id, :presence => true
  
  CLICK                     = 1
  EMAIL_ACQUIRED            = 2
  APPLIED                   = 3
  SIGNUP                    = 4
  MEMBERSHIP                = 5
  REGISTRATION              = 6
  UNSUBSCRIBED              = 7
  
  uniq_constants!
  
  def self.lookup(string)
    const_get(string.gsub(/\s/, "_").upcase)
  end
end

app/models/acquisition/acquisition_source.rb
class AcquisitionSource < ActiveRecord::Base
  belongs_to :acquisition_campaign
  
  def self.filter(params)
    finder = self
    finder = finder.where(:acquisition_campaign_id => params[:cmp]) if params[:cmp]
    finder.page(params[:page]).per(params[:per_page])
  end
  
  def clicked!(user)
    count!(user.try(:member?) ? :member_clicks : :nonmember_clicks)
    AcquisitionCohort.clicked!(acquisition_campaign, self, user)
  end
  
  def email_acquired!
    count!(:emails)
    AcquisitionCohort.email_acquired!(acquisition_campaign, self)
  end

  def applied!
    count!(:applications)
    AcquisitionCohort.applied!(acquisition_campaign, self)    
  end
  
  def signup!
    count!(:signups)
    AcquisitionCohort.signup!(acquisition_campaign, self)
  end
  
  def member!(membership)
    count!(:memberships)
    count!( membership.payment_method.billing_period == 1 ? 
              :monthly_subscribers : 
              :annual_subscribers) if membership.payment_method.respond_to?(:billing_period)
              
    AcquisitionCohort.member!(acquisition_campaign, self, membership)
  end

  def registration!
    count!(:registrations)
    AcquisitionCohort.registration!(acquisition_campaign, self)
  end

  def unsubscribed!
    count!(:unsubscriptions)
    AcquisitionCohort.unsubscribed!(acquisition_campaign, self)
  end

  def total_clicks
    member_clicks + nonmember_clicks
  end

  private
  
  def count!(field, amount=1)
    self.class.update_counters(id, field => amount)
  end
end

app/controllers/admin/acquisition/campaigns_controller.rb
class Admin::Acquisition::CampaignsController < Admin::BaseController
  def index
    @campaigns = AcquisitionCampaign.filter(params)
    @new_campaign = AcquisitionCampaign.new
  end
  
  def create
    @campaign = AcquisitionCampaign.new(params[:acquisition_campaign])
    if @campaign.save
      flash[:notice] = "Created Campaign #{@campaign.name}"
      redirect_to admin_acquisition_campaigns_path
    else
      flash[:error] = "There were errors. Please Try Again!"
      @new_campaign = @campaign
      render :action => :index
    end
  end
end

app/controllers/admin/acquisition/sources_controller.rb
class Admin::Acquisition::SourcesController < Admin::BaseController
  def index
    @sources = AcquisitionSource.filter(params)
    @new_source = AcquisitionSource.new
    @campaigns = AcquisitionCampaign.all
  end
  
  def create
    @source = AcquisitionSource.new(params[:acquisition_source])
    if @source.save
      flash[:notice] = "Created Source #{@source.name}"
      redirect_to admin_acquisition_sources_path
    else
      flash[:error] = "There were errors. Please Try Again!"
      @new_source = @source
      render :action => :index
    end
  end
  
end

app/controllers/admin/acquisition/sweepstakes_controller.rb
class Admin::Acquisition::SweepstakesController < Admin::BaseController
  def index
    @sweepstakes = Sweepstake.filter(params)
    @new_sweepstake ||= Sweepstake.new
    render :action => :index
  end
  
  def create
    @sweepstake = Sweepstake.new(params[:sweepstake])
    if @sweepstake.save
      flash[:notice] = "Created Sweepstake \"#{@sweepstake.name}\""
      redirect_to admin_acquisition_sweepstakes_path
    else
      flash[:error] = "There were errors. Please Try Again!"
      @new_sweepstake = @sweepstake
      index
    end
  end
  
  def edit
    @sweepstake = Sweepstake.find(params[:id])
  end
  
  def update
    @sweepstake = Sweepstake.find(params[:id])
    @sweepstake.attributes = params[:sweepstake]
    if @sweepstake.save
      flash[:notice] = "Saved Sweepstake \"#{@sweepstake.name}\""
      redirect_to admin_acquisition_sweepstake_path(@sweepstake)
    else
      flash[:error] = "There were errors. Please Try Again!"
      render :action => :edit
    end
  end
  
  def destroy
    @sweepstake = Sweepstake.find(params[:id])
    @sweepstake.destroy
    redirect_to admin_acquisition_sweepstakes_path
  end
  
  def show
    redirect_to edit_admin_acquisition_sweepstake_path(params[:id])
  end
end

app/controllers/site/sweepstakes_controller.rb
class Site::SweepstakesController < Site::BaseController
  before_filter :require_sweepstake
  layout 'site'
  
  def show
    @entry = @sweepstake.entries.find_or_initialize_by_invite_request_id(invite_request.try(:id))
    @entry.invite_request ||= InviteRequest.new
    @place = @sweepstake.place
    @page_description = "Enter to win a #{@sweepstake.short_summary} at #{@sweepstake.place_name}"
    @page_keywords = [@sweepstake.place_name, "sweepstake", "on the house", "free", @sweepstake.short_summary]
    @referrer = SweepstakeEntry.find_by_referral_code(params[:ref]) if params[:ref]
    render :action => :show
  end
  
  def enter
    @request = InviteRequest.with_attributes params[:entry].except("referred_by_id")
    if success = @request.save
      set_invite_request @request
      @entry = @sweepstake.entries.find_or_initialize_by_invite_request_id(@request.id)
      @entry.referred_by_id = params[:entry][:referred_by_id]
      success = @entry.save
    end
    
    respond_to do |format|
      if success
        format.html { redirect_to sweepstake_path(@sweepstake) }
        format.js { render :json => { :success => true, :entry => @entry, :html => render_to_string(:partial => "entry") } }
      else
        format.html { redirect_to sweepstake_path(@sweepstake) }
        format.js { render :json => { :success => false, :errors => @entry.errors.full_messages} }
      end
    end
  end
  
  def rules
    render :layout => "oreo"
  end

  private
  
  def require_sweepstake
    @sweepstake = Sweepstake.find(params[:id])
  end
end

app/views/admin/acquisition/sweepstakes/_form.html.haml
=spot_form_for [:admin, :acquisition, sweepstake], :display => "light clearfix inlinelabels" do |f|
  =f.hidden_field :place_id
  =f.text_field :name, :placeholder => "sweepstake name", :required => true, :label => "Name : ", :maxlength => 30
  =f.text_field :place_name, :placeholder => "place name", :required => true, :label => "Place Name : "
  =f.text_field :short_summary, :placeholder => "short summary", :required => true, :label => "Short Summary : ", :maxlength => 30
  =f.text_field :grand_prize, :placeholder => "grand prize", :required => true, :label => "Grand Prize : "
  =f.text_field :prize_value, :placeholder => "prize value", :required => true, :label => "Prize Value : ", :min => 0
  =f.text_area  :description, :required => true, :container_class => "tinymce", :label => "Full Desc. : "
  =f.text_field :starts_on, :placeholder => "start date", :required => true, :container_class => "dateinput", :value => sweepstake.starts_on.try(:strftime, '%A, %B %d, %Y'), :label => "Start Date : "
  =f.text_field :ends_on, :placeholder => "end date", :required => true, :container_class => "dateinput", :value => sweepstake.ends_on.try(:strftime, '%A, %B %d, %Y'), :label => "End Date : "
  %li.buttons
    =button_tag :class => 'tf btnorg300x41' do
      submit

app/views/admin/acquisition/sweepstakes/edit.html.haml
.manager
  %h1.sweepstake_title.title.clearfix
    =link_to "Sweepstake", admin_acquisition_sweepstakes_path
    =" : \"#{@sweepstake.name}\""
  .clearfix
    .left.preview
      =image_tag @sweepstake.place.image.url(:i640x400), :size => "320x200", :alt => @sweepstake.place.name
      %h2.tf=@sweepstake.place.name
      %h1.tf=@sweepstake.short_summary
      .description=@sweepstake.description.html_safe
  
    .formcontainer.left
      =render :partial => "form", :locals => {:sweepstake => @sweepstake}

=content_for :scripts do
  =javascript_include_tag 'vendor/tiny_mce/jquery.tinymce.js'

app/views/admin/acquisition/sweepstakes/index.html.haml
.manager
  .top.clearfix
    .pagination
      -unless @sweepstakes.last_page?
        .next=link_to "Next &rarr;".html_safe, admin_acquisition_sweepstakes_path(filters.merge(:page => @sweepstakes.current_page + 1))
      -unless @sweepstakes.first_page?
        .previous=link_to "&larr; Previous".html_safe, admin_acquisition_sweepstakes_path(filters.merge(:page => @sweepstakes.current_page - 1))
    %h1.title="#{pluralize(@sweepstakes.total_count, "Sweepstake")}"

  %table.data
    %thead
      %tr
        %th Id
        %th Place
        %th Summary
        %th Run Dates
        %th Entries
        %th Submissions
        %th Viral Multiplier
        %th Status
        %th Actions
    %tbody
      -@sweepstakes.to_a.each do |swpstk|
        %tr.center.sweepstake{:id => dom_id(swpstk), :class => cycle("even", "odd")}
          -place = swpstk.place
          %td= swpstk.id
          %td= link_to swpstk.place.name, admin_place_path(swpstk.place)
          %td= swpstk.short_summary
          %td= "#{swpstk.starts_on.strftime('%B %d, %Y')} - #{swpstk.ends_on.strftime('%B %d, %Y')}"
          %td= swpstk.entries_count
          %td= swpstk.submission_count
          %td= number_with_precision(swpstk.viral_factor, :precision => 2)
          %td= swpstk.status
          %td
            =link_to "Delete", admin_acquisition_sweepstake_path(swpstk), "data-method" => "delete", "data-confirm" => "Are you sure?"
            \|
            =link_to "Edit", edit_admin_acquisition_sweepstake_path(swpstk)
            \|
            =link_to "Preview", sweepstake_path(swpstk)
  .pagination.bottom
    -unless @sweepstakes.last_page?
      .next=link_to "Next &rarr;".html_safe, admin_acquisition_sweepstakes_path(params.slice('filter').merge(:page => @sweepstakes.current_page + 1))
    -unless @sweepstakes.first_page?
      .previous=link_to "&larr; Previous".html_safe, admin_acquisition_sweepstakes_path(params.slice('filter').merge(:page => @sweepstakes.current_page - 1))

  .form.new.clearfix
    %h2 New Sweepstake
    =render :partial => "form", :locals => {:sweepstake => @new_sweepstake}

=content_for :scripts do
  =javascript_include_tag 'vendor/tiny_mce/jquery.tinymce.js'